name: Deploy to backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.A90L }}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mohammad-backend:latest

  deploy:
    runs-on: [self-hosted,]
    needs: build

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: mohammad
          key: ${{ secrets.MOHAMMAD_SSH_KEY }}
          script: |
            cd /home/mohammad/week3_repo

            echo "${{ secrets.MOHAMMAD_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker compose down backend || true
            docker compose pull backend || true
            docker compose up -d backend
