name: Self-Hosted CI/CD

on:
  push:
    branches: [ "main" ]
jobs:
  
  hadolint:
    runs-on: self-hosted

    steps:
      - name: Run Hadolint on all existing Dockerfiles
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "**/Dockerfile"
          recursive: true

  build-and-push:
    needs: hadolint
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.A90L }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: ghcr.io/moammad-02/week3_repo/project:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: ghcr.io/moammad-02/week3_repo/project/templates:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.A90L }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull latest images
        run: |
           docker pull ghcr.io/moammad-02/week3_repo/project:latest && docker pull ghcr.io/moammad-02/week3_repo/project/templates:latest
           docker pull ghcr.io/moammad-02/week3_repo/project:latest && docker pull ghcr.io/moammad-02/week3_repo/project:latest

      - name: Run new containers
        run: |
           cd /home/cybersecurity/Desktop/week3_repo/project
           docker-compose down
           docker system prune -f
           docker-compose up -d
